# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFsxGC5vbnmTyH6UPcVIIHdRneh0sNdY
"""

words = open('names.txt','r').read().splitlines()

words[:10]

b={}
for w in words:
  chs= ['<S>'] + list(w)+ ['<E>']
  for ch1, ch2 in zip(chs , chs[1:]):
    bigram=(ch1,ch2)
    b[bigram]= b.get(bigram,0)+1

sorted(b.items(), key=lambda kv: -kv[1])

import torch

N = torch.zeros((27,27), dtype=torch.int32)

chars = sorted(list(set(''.join(words))))
stoi={s:i+1 for i,s in enumerate(chars)}
stoi['.']=0
itos= {i:s for s,i in stoi.items()}

for w in words:
  chs= ['.'] + list(w)+ ['.']
  for ch1, ch2 in zip(chs , chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    N[ix1,ix2]+=1

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
plt.figure(figsize=(16,16))
plt.imshow(N,cmap='Blues')
for i in range(27):
  for j in range(27):
    chstr=itos[i]+itos[j]
    plt.text(j,i,chstr,ha="center", va="bottom", color='gray')
    plt.text(j,i,N[i,j].item(),ha="center", va="top", color='gray')
plt.axis('off')

p = N[0].float()
p= p/p.sum()
p

g= torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

g= torch.Generator().manual_seed(2147483647)
p= torch.rand(3 ,generator=g)
p= p/p.sum()
p

torch.multinomial(p, num_samples=20, replacement=True, generator=g)

P = (N+1).float()
P /= P.sum(1, keepdim=True)

g= torch.Generator().manual_seed(2147483647)
for i in range(5):
  ix=0
  out=[]
  while True:
    p = P[ix]
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix ==0:
      break

  print(''.join(out))

log_likelihood=0.0
n=0
for w in words:
  chs= ['.'] + list(w)+ ['.']
  for ch1, ch2 in zip(chs , chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    prob = P[ix1,ix2]
    logprob= torch.log(prob)
    log_likelihood += logprob
    n+=1
    #print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')
print(log_likelihood)
nll = -log_likelihood
print(nll)
print(nll/n)

xs , ys = [],[]
for w in words[:1]:
  chs= ['.'] + list(w)+ ['.']
  for ch1, ch2 in zip(chs , chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)

xs=torch.tensor(xs)
ys=torch.tensor(ys)

import torch.nn.functional as F

xenc=F.one_hot(xs,num_classes=27).float()

g= torch.Generator().manual_seed(2147483647)
W=torch.randn((27,27),generator=g, requires_grad=True)
xenc @ W

logits=(xenc @ W)
counts=logits.exp()
probs = counts / counts.sum(1,keepdims=True)
probs

nlls= torch.zeros(5)
for i in range(5):
  x=xs[i].item()
  y=ys[i].item()
  print(f'bigram example {i+1} : {itos[x]}, {itos[y]} ( indexes {x},{y})')
  print(f'input the neural net: {x}')
  print(f'output probabilities :{probs[i]}')
  print(f'label {y}')
  p = probs[i ,y]
  print("probability assigned by the net to the the correct answer:",p.item())
  logp=torch.log(p)
  print("log likelihood",logp.item())
  nll=-logp
  print("negative log likelihood",nll.item())
  nlls[i]=nll
print("------")
print("average nll loss:",nlls.mean().item())

loss= -probs[torch.arange(5), ys].log().mean()

W.grad= None
loss.backward()

W.grad

xs, ys = [], []
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ', num)

# initialize the 'network'
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27, 27), generator=g, requires_grad=True)

for k in range(50):
  xenc=F.one_hot(xs,num_classes=27).float()
  logits=(xenc @ W)
  counts=logits.exp()
  probs = counts / counts.sum(1,keepdims=True)
  loss= -probs[torch.arange(num), ys].log().mean() + 0.1 * (W**2).mean()
  print(loss.item())

  W.grad= None
  loss.backward()
  W.data += -1 * W.grad

print(xs.shape, ys.shape, probs.shape)

import pandas as pd

df=pd.read_csv('turkce_isim.csv')

df.head(3)

words = df["name"].tolist()

import torch

N = torch.zeros((30,30), dtype=torch.int32)

wordssss = []
for w in words:
  a=list(w)
  if 'x' in a:
    print(1)
  elif 'w' in a:
    print(1)
  else:
    wordssss.append(w)


print(len(words))
print(len(wordssss))


words = wordssss

chars = sorted(list(set(''.join(words))))
stoi={s:i+1 for i,s in enumerate(chars)}
stoi['.']=0
itos= {i:s for s,i in stoi.items()}
print(chars)
len(chars)

for w in words:
  chs= ['.'] + list(w)+ ['.']
  for ch1, ch2 in zip(chs , chs[1:]):

    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    N[ix1,ix2]+=1

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
plt.figure(figsize=(16,16))
plt.imshow(N,cmap='Blues')
for i in range(30):
  for j in range(30):
    chstr=itos[i]+itos[j]
    plt.text(j,i,chstr,ha="center", va="bottom", color='gray')
    plt.text(j,i,N[i,j].item(),ha="center", va="top", color='gray')
plt.axis('off')

p = N[0].float()
p= p/p.sum()
p

import torch

g= torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

g= torch.Generator().manual_seed(2147483647)
p= torch.rand(3 ,generator=g)
p= p/p.sum()
p

torch.multinomial(p, num_samples=20, replacement=True, generator=g)

P = (N+1).float()
P /= P.sum(1, keepdim=True)

g= torch.Generator().manual_seed(2147483647+2)
for i in range(8):
  ix=0
  out=[]
  while True:
    p = P[ix]
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix ==0:
      break

  print(''.join(out))

log_likelihood=0.0
n=0
for w in words:
  chs= ['.'] + list(w)+ ['.']
  for ch1, ch2 in zip(chs , chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    prob = P[ix1,ix2]
    logprob= torch.log(prob)
    log_likelihood += logprob
    n+=1
    #print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')
print(log_likelihood)
nll = -log_likelihood
print(nll)
print(nll/n)

xs , ys = [],[]
for w in words:
  chs= ['.'] + list(w)+ ['.']
  for ch1, ch2 in zip(chs , chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)

xs=torch.tensor(xs)
ys=torch.tensor(ys)

import torch.nn.functional as F

xenc=F.one_hot(xs,num_classes=30).float()

g= torch.Generator().manual_seed(2147483647)
W=torch.randn((30,30),generator=g, requires_grad=True)
xenc @ W

logits=(xenc @ W)
counts=logits.exp()
probs = counts / counts.sum(1,keepdims=True)
probs

print(xs.shape)
print(ys.shape)
print(probs.shape)

nlls= torch.zeros(5)
for i in range(5):
  x=xs[i].item()
  y=ys[i].item()
  print(f'bigram example {i+1} : {itos[x]}, {itos[y]} ( indexes {x},{y})')
  print(f'input the neural net: {x}')
  print(f'output probabilities :{probs[i]}')
  print(f'label {y}')
  p = probs[i ,y]
  print("probability assigned by the net to the the correct answer:",p.item())
  logp=torch.log(p)
  print("log likelihood",logp.item())
  nll=-logp
  print("negative log likelihood",nll.item())
  nlls[i]=nll
print("------")
print("average nll loss:",nlls.mean().item())

xs, ys = [], []
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ', num)

# initialize the 'network'
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((30, 30), generator=g, requires_grad=True)

for k in range(50):
  xenc=F.one_hot(xs,num_classes=30).float()
  logits=(xenc @ W)
  counts=logits.exp()
  probs = counts / counts.sum(1,keepdims=True)
  loss= -probs[torch.arange(num), ys].log().mean() + 0.1 * (W**2).mean()
  print(loss.item())

  W.grad= None
  loss.backward()
  W.data += -1 * W.grad